# Start with this base image
FROM ubuntu:18.04

MAINTAINER Ben Yanke <ben@benyanke.com>

# Install needed packages to get PPAs
RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y git apt-transport-https ca-certificates curl software-properties-common --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install PHP packages
RUN add-apt-repository -y ppa:ondrej/php && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y \
      unzip \
      php7.1 \
      php7.1-gd \
      php7.1-xml \
      php-mbstring \
      php7.1-opcache \
      php7.1-mbstring \
      php7.1-zip \
    --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install node to run webpack (to ensure it compiles) as well as packages always needed
# RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - && apt-get install nodejs && apt-get clean && rm -rf /var/lib/apt/lists/* && npm install --global cross-env

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install Python Elastic Beanstalk Tooling
# RUN pip install setuptools && pip install wheel && pip install awsebcli
